[project]
name = "zed-scrapy-playwright"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhouzhouos", email = "leisure-zyf@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.62.0",
    "playwright-stealth>=2.0.3",
    "scrapy>=2.18.0",
]

[project.scripts]
zed-scrapy-playwright = "zed_scrapy_playwright:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
