[project]
name = "zed-scrapy-playwright"
version = "0.2.1"
description = "Less meta-dict config, more functional coding. Schedule browser pages as easily as CSS selectors."
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [
    { name = "zhouzhouos", email = "leisure-zyf@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "icecream>=2.2.0",
    "playwright>=1.62.0",
    "playwright-stealth>=2.0.3",
    "pytest>=9.1.1",
    "scrapy>=2.18.0",
]

[project.scripts]
zed-scrapy-playwright = "zed_scrapy_playwright:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
